security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_provider:
      chain:
        providers: [app_user_provider, manager_provider]
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    manager_provider:
      entity:
        class: App\Entity\Manager
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_provider
      custom_authenticator: App\Security\AppAuthenticator
      logout:
        path: app_logout
  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/manager, roles: ROLE_MANAGER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
